[project]
name = "lxr-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robin Burke", email = "rburke2233@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
lxr-eval = "lxr_eval:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
